substitutions:
  name: esp32-c6-multisensor-pro
  friendly_name: ESP32-C6 MultiSensor Pro

packages:
  # Device and board
  device: !include include/multisensor-pro/multisensor-pro-device.yaml
  board: !include include/multisensor-pro/multisensor-pro-board.yaml

  # Common
  api: !include include/common/api.yaml
  ota: !include include/common/ota.yaml
  wifi: !include include/common/wifi.yaml

  # Interfaces
  i2c: !include include/multisensor-pro/multisensor-pro-i2c.yaml
  spi: !include include/multisensor-pro/multisensor-pro-spi.yaml
  uart: !include include/multisensor-pro/multisensor-pro-uart.yaml

  # Components
  display: !include include/multisensor-pro/multisensor-pro-display.yaml
  ld24xx: !include include/multisensor-pro/multisensor-pro-ld24xx.yaml
  ads1220: !include include/multisensor-pro/multisensor-pro-ads1220.yaml
  dht22: !include include/multisensor-pro/multisensor-pro-dht22.yaml
  veml7700: !include include/multisensor-pro/multisensor-pro-veml7700.yaml
  sgp4x: !include include/multisensor-pro/multisensor-pro-sgp4x.yaml
  bme280: !include include/multisensor-pro/multisensor-pro-bme280.yaml
  mq7: !include include/multisensor-pro/multisensor-pro-mq7.yaml
  status_led: !include include/multisensor-pro/multisensor-pro-status-led.yaml
  time: !include include/multisensor-pro/multisensor-pro-time.yaml

# Enable logging
logger:
  # UART must be disabled if both are in use (LD24xx and 5v UART)
  baud_rate: 0
  #hardware_uart: USB_CDC
  
captive_portal:
    

